### ISSUE TITLE
Update contract docs

### ISSUE THREAD

**Issue by rmeissner** [safe-global/safe-docs#39]
- [x] Include general changes for [1.3.0](https://github.com/gnosis/safe-contracts/issues/260)
- [x] Improve documentation about [`safeTxGas`](https://github.com/gnosis/safe-contracts/issues/282)
- [ ] Add documentation about [HandlerContext](https://github.com/gnosis/safe-contracts/issues/246)
- [ ] Add documentation for [EIP-1271](https://github.com/gnosis/safe-contracts/issues/120)
